//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_Skill
    {
        public int Id_Profile_Skill { get; set; }
        public int Id_Profile { get; set; }
        public int Id_Skill { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
