//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Profile_Follow
    {
        public Nullable<int> Follower_id { get; set; }
        public int Followed_id { get; set; }
        public string Phone { get; set; }
        public string FullName { get; set; }
        public string Adress { get; set; }
        public string Image { get; set; }
        public string Descreption { get; set; }
        public string TargetJob { get; set; }
        public bool Status { get; set; }
        public bool Is_View { get; set; }
        public int Id_Profile { get; set; }
    }
}
