//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Profile
    {
        public int Id_Profile { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string Image { get; set; }
        public int Sex { get; set; }
        public string Hobbies { get; set; }
        public string Descreption { get; set; }
        public string TargetJob { get; set; }
        public bool Status { get; set; }
        public bool Is_View { get; set; }
        public string ExperienceName { get; set; }
        public bool Expr1 { get; set; }
        public string LanguageName { get; set; }
        public bool Expr2 { get; set; }
        public string SkillName { get; set; }
        public bool Expr3 { get; set; }
        public string ProjectName { get; set; }
        public bool Expr4 { get; set; }
        public string SpecializedName { get; set; }
        public bool Expr5 { get; set; }
        public string Email { get; set; }
        public bool Expr6 { get; set; }
        public string EducationName { get; set; }
        public bool Expr7 { get; set; }
        public string Ex_Descreptiom { get; set; }
        public string Ex_Date { get; set; }
        public string Pr_Descreption { get; set; }
    }
}
