//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Profile_Experience
    {
        public string ExperienceName { get; set; }
        public string Ex_Date { get; set; }
        public string Ex_Descreptiom { get; set; }
        public int Id_Profile { get; set; }
        public bool Status { get; set; }
    }
}
